# key- value

#41 => kocaeli 34 => istanbul

sehirler = ['kocaeli','istanbul']
 plakalar =[41,34]

 print(plakalar[sehirler.index('istanbul')])

#print(plakalar['kocaeli']) =>41
#print(plakalar['istanbul']) =>34

#plakalar = {'key' : 'value'}
# plakalar = {'kocaeli' : 41,'istanbul':34}

# print(plakalar['kocaeli'])
# print(plakalar['istanbul'])

# plakalar['ankara']=6
# plakalar['kocaeli']='new value'
# print(plakalar)
